---
- name: remove yum packaged ffmpeg
  become: yes
  yum: name=ffmpeg state=absent

# ffmpeg needs >= nasm-2.13
- name: add nasm repo
  become: yes
  template:
    src: nasm.repo
    dest: /etc/yum.repos.d/nasm.repo

- name: Install dependencies
  become: yes
  yum: name={{ item }} state=latest
  with_items:
    - autoconf
    - automake
    - cmake
    - freetype-devel
    - gcc
    - gcc-c++
    - git
    - libtool
    - make
    - mercurial
    - nasm
    - pkgconfig
    - zlib-devel
