---
- name: ffmpeg | Unarchive
  unarchive:
    src: https://ffmpeg.org/releases/ffmpeg-snapshot.tar.bz2
    dest: "{{ source_dir }}"
    copy: no

- name: Compile | ffmpeg
  become: yes
  shell: "export PATH=/usr/local/bin/:$PATH && {{ item }}"
  args:
    chdir: "{{ source_dir }}/ffmpeg"
    creates: "{{ bin_dir }}/ffmpeg"
  with_items:
    - PKG_CONFIG_PATH="{{ build_dir }}/lib/pkgconfig" ./configure --prefix={{ build_dir }} --pkg-config-flags="--static" --extra-cflags="-I{{ build_dir }}/include" --extra-ldflags="-L{{ build_dir }}/lib" --extra-libs=-lm --bindir={{ bin_dir }} --enable-gpl --enable-nonfree --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libfdk_aac
    - make
    - make install
    - make distclean
    - hash -d ffmpeg

- name: Symlink | ffmpeg
  become: yes
  file: state=link src=/usr/local/bin/ffmpeg dest=/usr/bin/ffmpeg
  
