---
# AAC audio encoder
- name: GIT clone | libfdk_aac
  git: repo=https://github.com/mstorsjo/fdk-aac.git
       dest={{ source_dir }}/libfdk_aac
       accept_hostkey=yes
       depth=1

- name: Compile | libfdk_aac
  become: yes
  shell: "export PATH=/usr/local/bin/:$PATH && {{ item }}"
  args:
    chdir: "{{ source_dir }}/libfdk_aac"
    creates: "{{ bin_dir }}/libfdk_aac"
  with_items:
    - autoreconf -fiv
    - ./configure --prefix={{ build_dir }} --disable-shared
    - make
    - make install
    - make distclean
