---
# - name: libmp3lame | Download
#   get_url: url=http://downloads.sourceforge.net/project/lame/lame/3.99/lame-3.99.5.tar.gz dest={{ source_dir }}/libmp3lame.tar.gz

- name: libmp3lame | Unarchive
  unarchive:
    remote_src: yes
    src: https://downloads.sourceforge.net/project/lame/lame/3.100/lame-3.100.tar.gz
    dest: "{{ source_dir }}"

- name: Compile | libmp3lame
  become: yes
  shell: "export PATH=/usr/local/bin/:$PATH && {{ item }}"
  args:
    chdir: "{{ source_dir }}/lame-3.99.5"
    creates: "{{ bin_dir }}/lame-3.99.5"
  with_items:
    - ./configure --prefix={{ build_dir }} --bindir={{ bin_dir }} --disable-shared --enable-nasm
    - make
    - make install
    - make distclean
