---
- name: libopus | Unarchive
  unarchive:
    src: https://archive.mozilla.org/pub/opus/opus-1.3.1.tar.gz
    dest: "{{ source_dir }}"
    copy: no

- name: Compile | libopus
  become: yes
  shell: "export PATH=/usr/local/bin/:$PATH && {{ item }}"
  args:
    chdir: "{{ source_dir }}/libopus"
    creates: "{{ bin_dir }}/libopus"
  with_items:
    - ./configure --prefix={{ build_dir }} --disable-shared
    - make
    - make install
    - make distclean
