---
- name: yasm | Unarchive
  unarchive:
    src: https://www.nasm.us/pub/nasm/releasebuilds/2.14.02/nasm-2.14.02.tar.bz2
    dest: "{{ source_dir }}"
    copy: no

- name: Compile | yasm
  become: yes
  shell: "export PATH=/usr/local/bin/:$PATH && {{ item }}"
  args:
    chdir: "{{ source_dir }}/nasm-2.14.02"
    creates: "{{ bin_dir }}/nasm"
  with_items:
    - ./autogen.sh
    - ./configure --prefix={{ build_dir }} --bindir={{ bin_dir }}
    - make
    - make install
    - make distclean
