---
- name: nasm | Unarchive
  unarchive:
    src: https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/nasm-2.15.05.tar.bz2
    dest: "{{ source_dir }}"
    copy: no

- name: Compile | nasm
  become: yes
  shell: "export PATH=/usr/local/bin/:$PATH && {{ item }}"
  args:
    chdir: "{{ source_dir }}/nasm-2.15.05"
    creates: "{{ bin_dir }}/nasm"
  with_items:
    - ./autogen.sh
    - ./configure --prefix={{ build_dir }} --bindir={{ bin_dir }}
    - make
    - make install
    - make distclean
