---
- name: yasm | Unarchive
  unarchive:
    src: https://www.tortall.net/projects/yasm/releases/yasm-1.3.0.tar.gz
    dest: "{{ source_dir }}"
    copy: no

- name: Compile | yasm
  become: yes
  shell: "export PATH=/usr/local/bin/:$PATH && {{ item }}"
  args:
    chdir: "{{ source_dir }}/yasm-1.3.0"
    creates: "{{ bin_dir }}/yasm"
  with_items:
    - ./configure --prefix={{ build_dir }} --bindir={{ bin_dir }}
    - make
    - make install
    - make distclean
